<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <None Include="Views\Shared\Partials\_Footer.cshtml" />
    <None Include="Views\Home\Partials\_MainContent.cshtml" />
    <None Include="Views\Shared\Partials\_Navbar.cshtml" />
  </ItemGroup>

</Project>
